# Generated by Django 4.2.2 on 2023-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('file', models.BinaryField(blank=True)),
                ('note_type', models.CharField(max_length=15)),
            ],
        ),
    ]
