# Generated by Django 4.2.2 on 2023-06-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='notes',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='file',
        ),
    ]
